<footer>
  <div class="footer_nav">
    <ul class="footer_links">
      <li><a href="index.php">Home</a></li>
      <li><a href="aboutme.php">About Me</a></li>
      <li><a href="posts.php">Update Posts</a></li>
      <li><a href="external_links.php">External Links</a></li>
    </ul>
  </div>

  <div id="footer_row">
    <a class="footer_link" href="https://github.com/Ollie-S23/OliverPortfolio_Website.git" target="_blank">
      Github Repo Link
    </a>
  </div>

  <p id="copyright">&copy; Copyright <?php echo date("Y"); ?> | Oliver Scott | All Rights Reserved</p>
</footer>
